services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: codemate-postgres
    environment:
      - 'POSTGRES_DB=codemate'
      - 'POSTGRES_PASSWORD=codemate'
      - 'POSTGRES_USER=codemate'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codemate"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
